// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace pRUEBA.Models
{
    public partial class ConversorBDContext : DbContext
    {
        public ConversorBDContext()
        {
        }

        public ConversorBDContext(DbContextOptions<ConversorBDContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Moneda> Moneda { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Moneda>(entity =>
            {
                entity.HasIndex(e => e.Code, "IX_Moneda_Code")
                    .IsUnique();

                entity.Property(e => e.Code)
                    .IsRequired()
                    .HasMaxLength(3);

                entity.Property(e => e.Name).IsRequired();

                entity.Property(e => e.Symbol).IsRequired();
            });

            modelBuilder.Entity<Pais>(entity =>
            {
                entity.Property(e => e.Name).IsRequired();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}